In [1]:
import numpy as np

## Creating array and multi dimentional array from a list

In [3]:
list1 = [1,2,3,4]

In [4]:
array1 = np.array(list1)

In [5]:
array1

array([1, 2, 3, 4])

In [6]:
list2 = [11,22,33,44]

In [7]:
mylist = [list1,list2]

In [8]:
mylist

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
array2 = np.array(mylist)

In [10]:
array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
array2.shape

(2, 4)

In [14]:
array2.dtype

dtype('int64')

## Different functions of an array 

In [17]:
np.zeros(5) #as point is there so they are decimals

array([0., 0., 0., 0., 0.])

In [16]:
zeroes_array = np.zeros(5)

In [18]:
zeroes_array

array([0., 0., 0., 0., 0.])

In [19]:
zeroes_array.dtype

dtype('float64')

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.ones([4,4]) #multi dimensional array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.eye(5) #creating on identity matrix with diagonal one 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
array3 = np.arange(5,50,2) # (start, last, step)

In [39]:
array3

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

## Arithmatic operations using array

In [26]:
array1

array([1, 2, 3, 4])

In [27]:
array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [30]:
array1 * array2 # multiplying 1D array with 2D array

array([[  1,   4,   9,  16],
       [ 11,  44,  99, 176]])

In [31]:
array1 - array2

array([[  0,   0,   0,   0],
       [-10, -20, -30, -40]])

In [32]:
1/array1

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [34]:
array1**2 # exponential operation

array([ 1,  4,  9, 16])

## Array Indexing

In [40]:
array3

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [42]:
array3[7]

19

In [43]:
array3[1:7]

array([ 7,  9, 11, 13, 15, 17])

In [44]:
array3[0:5]

array([ 5,  7,  9, 11, 13])

In [49]:
array3[:]

array([2000, 2000, 2000, 2000, 2000,   15,   17,   19,   21,   23,   25,
         27,   29,   31,   33,   35,   37,   39,   41,   43,   45,   47,
         49])

In [47]:
array3[0:5] = 2000 #assigned 2000 for first 5 items

In [48]:
array3

array([2000, 2000, 2000, 2000, 2000,   15,   17,   19,   21,   23,   25,
         27,   29,   31,   33,   35,   37,   39,   41,   43,   45,   47,
         49])

In [54]:
array_copy = array3.copy() #copying any array

In [55]:
array_copy

array([2000, 2000, 2000, 2000, 2000,   15,   17,   19,   21,   23,   25,
         27,   29,   31,   33,   35,   37,   39,   41,   43,   45,   47,
         49])

#####  2D array indexing

In [56]:
array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [60]:
array2[0]

array([1, 2, 3, 4])

In [61]:
array2[1][2]

33

In [63]:
array2[:,1:3]

array([[ 2,  3],
       [22, 33]])

## Matrix Processing

In [64]:
arr_mat = np.arange(50)

In [65]:
arr_mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [66]:
arr_mat = np.arange(50).reshape(10,5)

In [67]:
arr_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [69]:
arr_mat.T #transpose of a matrix

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [71]:
np.dot(arr_mat.T,arr_mat) #dot product

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

## Universal Functions

In [72]:
web = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(web)

True

In [ ]:
broad casting